#Create a deployment by using the image with tag 1.0 pushed to dockerhub as image
#Use containerPort 8081

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling-deployment
  labels:
    app: rolling-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rolling-app
  template:
    metadata:
      labels:
        app: rolling-app
    spec:
      containers:
      - name: rolling-app
        image: goyalsweta/sbservice-roll:2.0
        ports:
        - containerPort: 8081

